import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		padding: 16,
		backgroundColor: "#F0F4F8",
	},
	title: {
		textAlign: "center",
		fontSize: 24,
		fontWeight: "bold",
		marginBottom: 16,
		color: "#2D3748",
		fontFamily: "Work Sans",
	},
	productList: {
		paddingBottom: 16,
	},
	errorText: {
		fontSize: 18,
		color: "red",
		textAlign: "center",
		marginTop: 16,
	},
	loader: {
		marginTop: 16,
		alignSelf: "center",
	},
	downloadProgress: {
		position: "absolute",
		bottom: 20,
		left: 20,
		right: 20,
		backgroundColor: "rgba(255, 255, 255, 0.9)",
		padding: 10,
		borderRadius: 8,
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.25,
		shadowRadius: 3.84,
		elevation: 5,
	},
	modelContainer: {
		flex: 1,
		backgroundColor: "#FFFFFF",
	},
	modelView: {
		flex: 1,
		width: "100%",
		height: "100%",
		backgroundColor: "#F0F0F0",
	},
	modelLoader: {
		position: "absolute",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: "rgba(0, 0, 0, 0.7)",
		zIndex: 1000,
		alignItems: "center",
		justifyContent: "center",
	},
	progressText: {
		color: "#FFD8BC",
		marginTop: 10,
		fontSize: 14,
		fontWeight: "600",
	},
	modalContainer: {
		flex: 1,
		backgroundColor: '#441752',
		position: 'relative',
	},
	closeButton: {
		position: 'absolute',
        marginTop: 16,
		top: 40,
		right: 20,
		zIndex: 1,
		width: 30,
		height: 30,
		backgroundColor: 'rgba(255, 255, 255, 0.3)',
		borderRadius: 15,
		justifyContent: 'center',
		alignItems: 'center',
	},
	closeButtonText: {
		color: '#FFFFFF',
		fontSize: 18,
		fontWeight: 'bold',
	},
	glView: {
		flex: 1,
	},
});
